### ISSUE TITLE
Login/Logout don't work on docs.marklogic.com

### ISSUE THREAD

**Issue by dmcassel** [marklogic-community/RunDMC#528]
1. View docs.marklogic.com
2. Try to log in

No error is shown, but it doesn't log you in. 
1. View developer.marklogic.com
2. Log in
3. Click on documentation tab
4. try to log out

No error is shown but it doesn't log you out.

**Comment by kcoleman-marklogic** [comment]
A bump for great justice! I just got to rediscover this bug. :) When you go through the login flow from docs.marklogic.com, the login dialog just sits there, sneering at you, when you click the login button. I had to log in on the DMC home page to get it to work.

And, yeah, it doesn't log you out, either, if you're already logged in and go through the logout flow. It LOOKS like it logs you out, but the joke is on you.

**Comment by dmcassel** [comment]
Having deployed #343, the first personalization feature, this is now more important. The problem is that the login/logout requests are getting eaten by the rewriter, which thinks you probably want to see xdmp:login or xdmp:logout.

**Comment by dmcassel** [comment]
Edit profile has the same problem -- the endpoint isn't exposed by the rewriter.

**Comment by dmcassel** [comment]
fixed & deployed
