### ISSUE TITLE
Broken link in semantics tutorial

### ISSUE THREAD

**Issue by devinnicholson** [marklogic-community/RunDMC#696]
On https://developer.marklogic.com/learn/semantics-exercises/sparql-101, there is a link to SPARQL documentation at the very bottom that leads to https://docs.marklogic.com/guide/semantics/sparql which gives a 404. I tried looking around for a potential correct link, but wasn't quite sure what was intended.

**Comment by dmcassel** [comment]
Fixed -- thanks for pointing it out!
