### ISSUE TITLE
Node.js Client API JSDoc is not included in searches

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic-community/RunDMC#745]
AFAICT, we are not including the JSDoc generated content in searches when users search docs.marklogic.com. For example, if you search for something like "patchBuilder", which is one of the Node.js interfaces, you won't get any hits in the JSDoc, just a couple in the guide where it gets mentioned. You can replicate this with other search terms as well.

I'm not sure what magic makes the javadoc content get included in searches, but it needs to be extended to the JSDoc.

**Comment by dmcassel** [comment]
See https://github.com/marklogic-community/RunDMC/blob/master/src/model/data-access.xqy#L405-L428. When searching on docs, `$is-api` is true.

**Comment by kcoleman-marklogic** [comment]
Thanks for the pointer, @dmcassel . This line of that function looks particularly suspect:

https://github.com/marklogic-community/RunDMC/blob/master/src/model/data-access.xqy#L419

**Comment by dmcassel** [comment]
agreed

**Comment by kcoleman-marklogic** [comment]
Confirmed that this is the way to fix the basic search problem. 

The other half of this is to make the facets work. Currently, the hits in the jsdoc show up under a "Miscellaneous Pages" facet, which isn't very friendly of them. I think I know how and where to fix this, from chasing down how the Java Client facets work.

**Comment by kcoleman-marklogic** [comment]
I have a fix in hand. Waiting to hear back from Greg Nist if he wants his team to review it since it touches on the shared search code, rather than being specific to the doc portion of the app.

WRT facets, I got the facets working, but I punted on the facet icon. I just reused the folder icon that's the fallback icon. I refuse to get into hunting down some spiffy Node.js icon and adding it to the app.

**Comment by gregnist** [comment]
I have reviewed the code change and agree that it looks good. I also cagree with your decision not to change the icon. Thanks!

**Comment by kcoleman-marklogic** [comment]
@gregnist I haven't checked my changes in yet or put together a pull request, so that's pretty impressive. ;)

I was waiting to hear back whether you wanted to review the changes or not. Since you do, I'll submit a pull request and notify you. Thanks!

**Comment by kcoleman-marklogic** [comment]
@gregnist The pull request is here, if you would like to take a look.

https://github.com/marklogic-community/RunDMC/pull/750

Not sure how I managed not to attach it to this issue. Idiot loose on the keyboard. Anyway, if you're OK with it, I'll merge it. It'll go on the docapp branch for now, but I'll be merging docapp out to master in a couple days, in preparation for 9.0-4.

**Comment by kcoleman-marklogic** [comment]
Deployed and tested on pubs. Fix will be pushed with 9.0-4.
