### ISSUE TITLE
DMC sidebar now wraps at 1384 px and covers up doc nav controls

### ISSUE THREAD

**Issue by kcoleman-marklogic** [marklogic-community/RunDMC#800]
This commit causes a serious usability problem on docs.marklogic.com: 

https://github.com/marklogic-community/RunDMC/commit/c4ed51f2601bf419ff312dd666b676600c1502a8

If your browser is not at least 1382 px wide, the sub nav now wraps. On developer.marklogic.com, it "merely" looks bad. On docs.marklogic.com, it actually covers up one of the doc site navigation controls, which is a functional problem. 

Here's a screencap. Note I scrunched it up a lot more than is needed to provoke the problem, in the interests of viewability on github.

![image](https://user-images.githubusercontent.com/1951367/43733568-f9d00a52-9969-11e8-81aa-222be72b9198.png)

We've already had one Support case from a user who thought the XQuery function reference documentation was no longer available on the docs site because the pick list for navigating to it is buried under the sub nav.

There's plenty of room on the sub nav to accomodate the link that was added, so I assume an adjustment is needed to some fixed offset somewhere. We can't leave the site like this.

**Comment by TrinhML** [comment]
Fixed by removing the addition to the subnav. No opposition from stakeholders and since we are replatforming, I don't want to spend more cycles troubleshooting. 

https://github.com/marklogic-community/RunDMC/commit/08550459420a6b40178a8a4304603ee3a74f36e0
